services:
  app:
    ports:
      - "3000:3000"
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3010:3001"
  minio:
    ports:
      - "9000:9000"
      - "9001:9001"
